# 应用服务 WEB 访问端口
server:
  port: 8888
# 应用名称
spring:
  main:
    headless: false
  application:
    name: MedicalTaskScheduled
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taskscheduled?serverTimezone=GMT%2B8
    username: "root"
    password: "0612"
  # Redis 连接参数配置
  redis:
    host: 192.168.217.149
    port: 6379
    jedis:
      pool:
        max-wait: 100ms
    timeout: 100
#自定义属性 读取值

#project:
#  nickname: "JJLin's graduation design, MedicalTaskScheduled"
#  index:
#    cookie:
#      name: "name"
#      value: "JJLin"
#    redirectPath: "/accessIndexAgain"

#是否启用swagger2
swagger:
  enable: true

# 阿里云
aliyun:
  RAM:
    keyid: "LTAI5tS6M9xJYnQmKz2rWA2g"
    keysecret: "vqCsBvzVxQtyLI8p3qyH8zQC9GjjV3"
  endpoint: "dysmsapi.aliyuncs.com"
  signname: "在线个人项目"
  templatecode: "SMS_262435388"
  phonenumbers: "13669544812"

# 敏感词词库文件路径指定
sensitiveWordFilter:
  sensitiveWords:
    filePath:
